### PR TITLE
Another attempt at dynamic matrix

### PR DESCRIPTION
**Pull request by robg-answer**

### CODE REVIEW

**Comment by cmbuckley** [comment]
The terraform-docs@v1.0.0 is the only thing that uses `::set-output`, and it's actually fixed on main so might get a release in future: https://github.com/terraform-docs/gh-actions/blob/main/src/docker-entrypoint.sh#L180

**Comment by cmbuckley** [comment]
If we want to roll our own, here's a cut-down version:

```yaml
  determine-modules:
    name: "Determine Terraform Modules"
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.list-modules.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract dirs from Terraform_Modules
        id: list-modules
        run: |
          echo "modules=$(ls Terraform_modules | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
```

**Comment by robg-answer** [comment]
Ah am I missing outputs? Ill get that in tomorrow.

**Comment by robg-answer** [comment]
The latest thing I have is working, you need a seperate step for JQ as it's not installed.

**Comment by cmbuckley** [comment]
jq is installed by default in the base image, the example I posted is a complete job that does everything needed, see here: https://github.com/AnswerConsulting/AnswerKing-Infrastructure/actions/runs/4117096124/jobs/7107977458

**Review by JoeCSykes — APPROVED** [review]

**Review by cmbuckley — APPROVED** [review]

**Pull request merged**
